//  {
//     name: AppThemeName.PURPLE,
//     baseColor: '#7f017f',
//     fadeColor: 'rgba(127, 1, 127,0.1)',
//     tabColor: '#b200b2',
//     borderColor: '#fff',
//     textColor: '#fff',
//     contrastColor: '#fff',
//     bgColor: '#ffeaff',
//     textAlt: '#000',
//     bottomTabBg:'rgba(127, 1, 127,0.4)',
//     modal: {
//       title: '#000',
//       inputbg: '#fff',
//       inputBorder: '#7f017f',
//       inputText: '#000',
//       pickerbg: '#ffeaff',
//       pickerText: '#000',
//       saveBtnbg: '#7f017f',
//       saveBtnText: '#fff',
//     },
//     toggleBtn: {
//       bgActive: '#b200b2',
//       bgInactive: '#fff',
//       textActive: '#fff',
//       textInactive: '#000',
//     },
//     tab: {
//       label: '#7f017f',
//       bg: '#fff',
//       value: '#7f017f',
//       btnBg: '#7f017f',
//       btnText: '#fff',
//       icon: '#7f017f',
//       text: '#fff',
//     },
//     header: {textColor: '#fff'},
//   },


//  {
//     name: AppThemeName.YELLOW,
//     baseColor: '#ffc107',
//     fadeColor: '#rgba(255, 193, 7,0.1)',
//     tabColor: '#ffeb99',
//     borderColor: '#000',
//     textColor: '#000',
//     contrastColor: '#fff',
//     bgColor: '#fff8e1',
//     textAlt: '#000',
//     bottomTabBg:'rgba(255, 193, 7,0.4)',
//     modal: {
//       title: '#000',
//       inputbg: '#fff',
//       inputBorder: '#ffc107',
//       inputText: '#000',
//       pickerbg: '#fff8e1',
//       pickerText: '#000',
//       saveBtnbg: '#ffc107',
//       saveBtnText: '#fff',
//     },
//     toggleBtn: {
//       bgActive: '#ffeb99',
//       bgInactive: '#fff',
//       textActive: '#000',
//       textInactive: '#000',
//     },
//     tab: {
//       label: '#ffc107',
//       bg: '#fff',
//       value: '#ffc107',
//       btnBg: '#ffc107',
//       btnText: '#fff',
//       icon: '#ffc107',
//       text: '#fff',
//     },
//     header: {textColor: '#fff'},
//   },


// {
//     name: AppThemeName.CORAL,
//     baseColor: '#ff6f61',
//     fadeColor: 'rgba(255, 111, 97,0.1)',
//     tabColor: '#ff9478',
//     borderColor: '#fff',
//     textColor: '#fff',
//     contrastColor: '#fff',
//     bgColor: '#fff3f0',
//     textAlt: '#000',
//     bottomTabBg:'rgba(255, 111, 97,0.4)',
//     modal: {
//       title: '#000',
//       inputbg: '#fff',
//       inputBorder: '#ff6f61',
//       inputText: '#000',
//       pickerbg: '#fff3f0',
//       pickerText: '#000',
//       saveBtnbg: '#ff6f61',
//       saveBtnText: '#fff',
//     },
//     toggleBtn: {
//       bgActive: '#ff6f61',
//       bgInactive: '#fff',
//       textActive: '#fff',
//       textInactive: '#000',
//     },
//     tab: {
//       label: '#ff6f61',
//       bg: '#fff',
//       value: '#ff6f61',
//       btnBg: '#ff6f61',
//       btnText: '#fff',
//       icon: '#ff6f61',
//       text: '#fff',
//     },
//     header: {textColor: '#fff'},
//   },